# This config is only for the "shutdown overlay" instance of Kitty.
# We'll point Kitty at it with --config.

# Make the background partially transparent (only works on compositors that support it).
# If you’re using SwayFX with blur, any alpha area will be blurred with live motion behind it.
background_opacity 0.7

# Background/foreground colors
background #000000
foreground #ffffff

# If you want larger text
font_size 20

# Turn off the window title bar if you want (Sway is controlling borders anyway).
detect_wayland 1

